#!/usr/bin/env python3
"""Record the exact machine and package set that produced the published results.

Reviewers of the SoftwareX submission asked for a fully pinned reference
environment, the operating system and driver versions, checkpoint checksums,
and a statement of which tests run without a GPU or without the optional ONNX
extra. Writing that by hand invites drift, so it is generated here.

Run this on the reference machine, from the repository root:

  python scripts/collect_reference_environment.py

It writes requirements.lock and docs/reference-environment.md.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import re
import subprocess
import sys
from pathlib import Path

# Checkpoints the reproduction demos load. Paths are the ones recorded in
# expected_results/*.json plus the teacher copies those runs point at.
CHECKPOINT_GLOBS = [
    "runs/d1_cub200_teacher/best.pth",
    "runs/d2_cars196_teacher/best.pth",
    "runs/d3_sop_teacher/best.pth",
    "runs/d4_epillid_teacher/best.pth",
    "runs/20260717_164702_d1_cosine_s42/best.pth",
    "runs/20260718_084411_d2_cosine_s42/best.pth",
    "runs/20260719_030413_d3_cosine_s42/best.pth",
    "runs/20260719_054835_d4_epillid_cosine_s42/best.pth",
    "runs/20260719_054835_d4_cosine_s42/best.pth",
]


def run(cmd: list[str]) -> str:
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=30, check=False)
        return out.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""


def gpu_info() -> dict:
    line = run(["nvidia-smi",
                "--query-gpu=name,memory.total,driver_version",
                "--format=csv,noheader"])
    if not line:
        return {"name": "not detected", "memory": "", "driver": ""}
    parts = [p.strip() for p in line.splitlines()[0].split(",")]
    return {"name": parts[0], "memory": parts[1] if len(parts) > 1 else "",
            "driver": parts[2] if len(parts) > 2 else ""}


def os_info() -> str:
    for line in Path("/etc/os-release").read_text(encoding="utf-8").splitlines() \
            if Path("/etc/os-release").exists() else []:
        if line.startswith("PRETTY_NAME="):
            return line.split("=", 1)[1].strip('"')
    return platform.platform()


def torch_info() -> dict:
    import torch
    import torchvision
    return {
        "torch": str(torch.__version__),
        "torchvision": str(torchvision.__version__),
        "cuda": str(torch.version.cuda),
        "cudnn": str(torch.backends.cudnn.version()),
        "available": torch.cuda.is_available(),
    }


def freeze() -> list[str]:
    text = run([sys.executable, "-m", "pip", "freeze", "--all"])
    # Drop the editable self-reference: the lock pins the dependencies of this
    # package, not the package itself.
    return sorted(line for line in text.splitlines()
                  if line.strip() and "egg=embedkd" not in line)


def classify_tests() -> list[tuple[str, str]]:
    """Report which optional dependency each test file needs, from its own guard."""
    rows = []
    for path in sorted(Path("tests").glob("test_*.py")):
        text = path.read_text(encoding="utf-8")
        needs = sorted(set(re.findall(r'importorskip\(\s*["\']([\w.]+)["\']', text)))
        uses_cuda = bool(re.search(r'\bcuda\b', text))
        note = ", ".join(needs) if needs else "none"
        if uses_cuda:
            note += " (references cuda)"
        rows.append((path.name, note))
    return rows


def checksums() -> list[tuple[str, str, int]]:
    rows = []
    for rel in CHECKPOINT_GLOBS:
        p = Path(rel)
        if not p.exists():
            continue
        h = hashlib.sha256()
        with open(p, "rb") as fh:
            for chunk in iter(lambda: fh.read(1 << 20), b""):
                h.update(chunk)
        rows.append((rel, h.hexdigest(), p.stat().st_size))
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-lock", default="requirements.lock")
    parser.add_argument("--out-doc", default="docs/reference-environment.md")
    parser.add_argument("--torch-index", default="https://download.pytorch.org/whl/cu130",
                        help="index the CUDA build of torch was installed from")
    args = parser.parse_args()

    t = torch_info()
    g = gpu_info()
    pkgs = freeze()

    lock = [
        "# Reference environment for the published EmbedKD results.",
        "# Generated by scripts/collect_reference_environment.py; do not edit by hand.",
        "#",
        f"# Host          {platform.node()}",
        f"# OS            {os_info()}",
        f"# Kernel        {platform.release()}",
        f"# GPU           {g['name']}, {g['memory']}, driver {g['driver']}",
        f"# CUDA / cuDNN  {t['cuda']} / {t['cudnn']}",
        f"# Python        {platform.python_version()}",
        "#",
        "# torch and torchvision carry a CUDA build tag that PyPI does not serve.",
        f"# Install them first from {args.torch_index}, then install the rest:",
        f"#   pip install torch=={t['torch'].split('+')[0]} "
        f"torchvision=={t['torchvision'].split('+')[0]} --index-url {args.torch_index}",
        "#   pip install -r requirements.lock",
        "#",
        f"# Built torch tag {t['torch']}, torchvision tag {t['torchvision']}",
        "",
    ] + pkgs
    Path(args.out_lock).write_text("\n".join(lock) + "\n", encoding="utf-8")

    doc = [
        "# Reference environment",
        "",
        "Everything on this page is generated by",
        "`scripts/collect_reference_environment.py` on the machine that produced the",
        "published numbers. Regenerate it there rather than editing it.",
        "",
        "## Machine",
        "",
        "| Item | Value |",
        "|---|---|",
        f"| Host | {platform.node()} |",
        f"| Operating system | {os_info()} |",
        f"| Kernel | {platform.release()} |",
        f"| GPU | {g['name']} |",
        f"| GPU memory | {g['memory']} |",
        f"| NVIDIA driver | {g['driver']} |",
        f"| CUDA (as reported by torch) | {t['cuda']} |",
        f"| cuDNN | {t['cudnn']} |",
        f"| Python | {platform.python_version()} |",
        f"| torch | {t['torch']} |",
        f"| torchvision | {t['torchvision']} |",
        f"| Packages pinned in requirements.lock | {len(pkgs)} |",
        "",
        "## Installing the same environment",
        "",
        "The CUDA build tag is not available from PyPI, so torch comes from its own",
        "index first and the lock file supplies the rest.",
        "",
        "```bash",
        f"pip install torch=={t['torch'].split('+')[0]} "
        f"torchvision=={t['torchvision'].split('+')[0]} --index-url {args.torch_index}",
        "pip install -r requirements.lock",
        "pip install -e .",
        "```",
        "",
        "## Optional dependencies and GPU, per test file",
        "",
        "The guard in each file is the source of truth here; the table is read from it.",
        "No test requires a GPU: the whole suite runs on CPU, which is what continuous",
        "integration does on every push.",
        "",
        "| Test file | Skipped unless these are installed |",
        "|---|---|",
    ]
    for name, note in classify_tests():
        doc.append(f"| `{name}` | {note} |")

    rows = checksums()
    doc += [
        "",
        "## Checkpoint checksums",
        "",
        "SHA-256 of the checkpoints the reproduction demos load. Verify a download",
        "against this table before trusting a reproduction result.",
        "",
        "| Checkpoint | Bytes | SHA-256 |",
        "|---|---|---|",
    ]
    if rows:
        for rel, digest, size in rows:
            doc.append(f"| `{rel}` | {size} | `{digest}` |")
    else:
        doc.append("| (no checkpoints present on this machine) | | |")
    doc.append("")

    Path(args.out_doc).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out_doc).write_text("\n".join(doc) + "\n", encoding="utf-8")

    print(json.dumps({"lock": args.out_lock, "doc": args.out_doc,
                      "packages": len(pkgs), "checkpoints": len(rows)}, indent=2))


if __name__ == "__main__":
    main()
